### ISSUE TITLE
Low code coverage

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-afs#6]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Code coverage is  low and does not reflect real coverage.
2 reasons:
  - There is a lot of cross module coverage which is not reported by jacoco by default. We have tpp create a distribution module like in powsybl-core to compute a full project coverage.
  - Test are skipped in Cassandra storage and could be actived.

* **What is the expected behavior?**
A code coverage > 80%

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by pl-buiquang** [comment]
Can we close this now ?
